In [1]:
#!pip install torch 
#!pip install torchsummary
#!pip install torchvision


In [2]:
import torch
from datetime import datetime
import time
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchsummary import summary
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
from model_structure import CNN
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, confusion_matrix
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm


In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [4]:
model = CNN().to(device)

In [5]:
summary(model, (3, 224, 224))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 32, 224, 224]             896
              ReLU-2         [-1, 32, 224, 224]               0
         MaxPool2d-3         [-1, 32, 112, 112]               0
            Conv2d-4         [-1, 64, 112, 112]          18,496
              ReLU-5         [-1, 64, 112, 112]               0
         MaxPool2d-6           [-1, 64, 56, 56]               0
            Conv2d-7          [-1, 128, 56, 56]          73,856
              ReLU-8          [-1, 128, 56, 56]               0
         MaxPool2d-9          [-1, 128, 28, 28]               0
           Conv2d-10          [-1, 256, 28, 28]         295,168
             ReLU-11          [-1, 256, 28, 28]               0
        MaxPool2d-12          [-1, 256, 14, 14]               0
           Linear-13                  [-1, 512]      25,690,624
             ReLU-14                  [

In [6]:
loss_func = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                           std=[0.229, 0.224, 0.225])
    ])

In [7]:
model_number = 2
# Set data set directory
data_dir = f'RGB_data_for_model_{model_number}/train/'
test_dir = f'RGB_data_for_model_{model_number}/test/'

# Load data set
dataset = datasets.ImageFolder(data_dir,transform=transform)
test_dataset = datasets.ImageFolder(test_dir,transform=transform)

batch_size = 32
train_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    

In [8]:
print(f"Noof classes: {len(dataset.classes)}")
print(f"Classes: {dataset.classes}")
print(f"Total samples: {len(dataset)}")

Noof classes: 2
Classes: ['asquirrel', 'dog']
Total samples: 3000


In [9]:
num_epochs = 50

In [10]:
train_losses = []
test_metrics = {
    'accuracy': [], 'f1': [], 
    'precision': [], 'recall': []
}

for epoch in range(num_epochs):
    start_time = time.time()
    
    # Training Phase
    model.train()
    train_loss = 0.0
    train_preds = []
    train_targets = []
    
    # Progress bar for training
    train_pbar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{num_epochs} [Train]')
    
    for inputs, labels in train_pbar:
        inputs = inputs.to(device)
        labels = labels.float().to(device)
        
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = loss_func(outputs.squeeze(), labels)
        
        loss.backward()
        optimizer.step()
        
        train_loss += loss.item()
        
        # Store predictions and targets for metrics
        preds = (outputs.squeeze() > 0.5).float().cpu().detach().numpy()
        train_preds.extend(preds)
        train_targets.extend(labels.cpu().numpy())
        
        # Update progress bar
        train_pbar.set_postfix({'loss': f'{loss.item():.4f}'})
    
    avg_train_loss = train_loss / len(train_loader)
    train_losses.append(avg_train_loss)
    
    # Testing Phase
    model.eval()
    test_loss = 0.0
    test_preds = []
    test_targets = []
    
    # Progress bar for testing
    test_pbar = tqdm(test_loader, desc=f'Epoch {epoch+1}/{num_epochs} [Test]')
    
    with torch.no_grad():
        for inputs, labels in test_pbar:
            inputs = inputs.to(device)
            labels = labels.float().to(device)
            
            outputs = model(inputs)
            loss = loss_func(outputs.squeeze(), labels)
            test_loss += loss.item()
            
            preds = (outputs.squeeze() > 0.5).float().cpu().numpy()
            test_preds.extend(preds)
            test_targets.extend(labels.cpu().numpy())
    
    # Calculate metrics
    test_accuracy = accuracy_score(test_targets, test_preds)
    test_f1 = f1_score(test_targets, test_preds, zero_division=0)
    test_precision = precision_score(test_targets, test_preds, zero_division=0)
    test_recall = recall_score(test_targets, test_preds, zero_division=0)
    
    # Store metrics
    test_metrics['accuracy'].append(test_accuracy)
    test_metrics['f1'].append(test_f1)
    test_metrics['precision'].append(test_precision)
    test_metrics['recall'].append(test_recall)
    
    # Calculate confusion matrix
    cm = confusion_matrix(test_targets, test_preds)
    
    # Calculate time taken for epoch
    epoch_time = time.time() - start_time
    
    # Print detailed metrics
    print(f'\nEpoch {epoch+1}/{num_epochs} - Time: {epoch_time:.2f}s')
    print(f'Train Loss: {avg_train_loss:.4f}')
    print(f'Test Loss: {test_loss/len(test_loader):.4f}')
    print('\nTest Metrics:')
    print(f'Accuracy: {test_accuracy:.4f}')
    print(f'F1 Score: {test_f1:.4f}')
    print(f'Precision: {test_precision:.4f}')
    print(f'Recall: {test_recall:.4f}')
    print('\nConfusion Matrix:')
    print(cm)
    print('-' * 60)
    times = datetime.now().strftime("%Y_%m_%d_%H_%M_%S")
    if test_f1 == max(test_metrics['f1']):
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'train_loss': avg_train_loss,
            'test_metrics': test_metrics
        }, f'CNN_model_{model_number}_final_{times}.pth')
    

Epoch 1/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  3.51it/s]



Epoch 1/50 - Time: 39.74s
Train Loss: 0.6586
Test Loss: 0.5125

Test Metrics:
Accuracy: 0.7300
F1 Score: 0.7245
Precision: 0.7396
Recall: 0.7100

Confusion Matrix:
[[75 25]
 [29 71]]
------------------------------------------------------------


Epoch 2/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  8.58it/s]



Epoch 2/50 - Time: 19.13s
Train Loss: 0.4949
Test Loss: 0.4044

Test Metrics:
Accuracy: 0.7900
F1 Score: 0.7941
Precision: 0.7788
Recall: 0.8100

Confusion Matrix:
[[77 23]
 [19 81]]
------------------------------------------------------------


Epoch 3/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  8.03it/s]



Epoch 3/50 - Time: 19.39s
Train Loss: 0.4259
Test Loss: 0.3657

Test Metrics:
Accuracy: 0.8500
F1 Score: 0.8673
Precision: 0.7778
Recall: 0.9800

Confusion Matrix:
[[72 28]
 [ 2 98]]
------------------------------------------------------------


Epoch 4/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.51it/s]



Epoch 4/50 - Time: 21.62s
Train Loss: 0.3646
Test Loss: 0.3700

Test Metrics:
Accuracy: 0.8200
F1 Score: 0.8144
Precision: 0.8404
Recall: 0.7900

Confusion Matrix:
[[85 15]
 [21 79]]
------------------------------------------------------------


Epoch 5/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  7.03it/s]



Epoch 5/50 - Time: 23.22s
Train Loss: 0.3167
Test Loss: 0.3160

Test Metrics:
Accuracy: 0.8400
F1 Score: 0.8400
Precision: 0.8400
Recall: 0.8400

Confusion Matrix:
[[84 16]
 [16 84]]
------------------------------------------------------------


Epoch 6/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.46it/s]



Epoch 6/50 - Time: 21.65s
Train Loss: 0.2984
Test Loss: 0.3217

Test Metrics:
Accuracy: 0.8300
F1 Score: 0.8247
Precision: 0.8511
Recall: 0.8000

Confusion Matrix:
[[86 14]
 [20 80]]
------------------------------------------------------------


Epoch 7/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  8.34it/s]



Epoch 7/50 - Time: 22.58s
Train Loss: 0.2411
Test Loss: 0.2488

Test Metrics:
Accuracy: 0.8800
F1 Score: 0.8788
Precision: 0.8878
Recall: 0.8700

Confusion Matrix:
[[89 11]
 [13 87]]
------------------------------------------------------------


Epoch 8/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  3.71it/s]



Epoch 8/50 - Time: 29.78s
Train Loss: 0.1899
Test Loss: 0.4250

Test Metrics:
Accuracy: 0.8350
F1 Score: 0.8533
Precision: 0.7680
Recall: 0.9600

Confusion Matrix:
[[71 29]
 [ 4 96]]
------------------------------------------------------------


Epoch 9/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  7.43it/s]



Epoch 9/50 - Time: 34.26s
Train Loss: 0.1625
Test Loss: 0.3376

Test Metrics:
Accuracy: 0.8750
F1 Score: 0.8731
Precision: 0.8866
Recall: 0.8600

Confusion Matrix:
[[89 11]
 [14 86]]
------------------------------------------------------------


Epoch 10/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  8.59it/s]



Epoch 10/50 - Time: 23.61s
Train Loss: 0.1329
Test Loss: 0.4086

Test Metrics:
Accuracy: 0.8800
F1 Score: 0.8846
Precision: 0.8519
Recall: 0.9200

Confusion Matrix:
[[84 16]
 [ 8 92]]
------------------------------------------------------------


Epoch 11/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.36it/s]



Epoch 11/50 - Time: 25.92s
Train Loss: 0.0798
Test Loss: 0.4333

Test Metrics:
Accuracy: 0.8650
F1 Score: 0.8615
Precision: 0.8842
Recall: 0.8400

Confusion Matrix:
[[89 11]
 [16 84]]
------------------------------------------------------------


Epoch 12/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.69it/s]



Epoch 12/50 - Time: 24.35s
Train Loss: 0.0604
Test Loss: 1.2768

Test Metrics:
Accuracy: 0.8750
F1 Score: 0.8826
Precision: 0.8319
Recall: 0.9400

Confusion Matrix:
[[81 19]
 [ 6 94]]
------------------------------------------------------------


Epoch 13/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.45it/s]



Epoch 13/50 - Time: 30.51s
Train Loss: 0.0636
Test Loss: 0.4489

Test Metrics:
Accuracy: 0.8700
F1 Score: 0.8785
Precision: 0.8246
Recall: 0.9400

Confusion Matrix:
[[80 20]
 [ 6 94]]
------------------------------------------------------------


Epoch 14/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  7.36it/s]



Epoch 14/50 - Time: 24.08s
Train Loss: 0.0802
Test Loss: 0.3920

Test Metrics:
Accuracy: 0.8800
F1 Score: 0.8835
Precision: 0.8585
Recall: 0.9100

Confusion Matrix:
[[85 15]
 [ 9 91]]
------------------------------------------------------------


Epoch 15/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.50it/s]



Epoch 15/50 - Time: 23.57s
Train Loss: 0.0370
Test Loss: 0.8317

Test Metrics:
Accuracy: 0.8850
F1 Score: 0.8920
Precision: 0.8407
Recall: 0.9500

Confusion Matrix:
[[82 18]
 [ 5 95]]
------------------------------------------------------------


Epoch 16/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.69it/s]



Epoch 16/50 - Time: 26.79s
Train Loss: 0.0225
Test Loss: 0.9731

Test Metrics:
Accuracy: 0.8950
F1 Score: 0.8986
Precision: 0.8692
Recall: 0.9300

Confusion Matrix:
[[86 14]
 [ 7 93]]
------------------------------------------------------------


Epoch 17/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.57it/s]



Epoch 17/50 - Time: 24.66s
Train Loss: 0.0270
Test Loss: 0.5904

Test Metrics:
Accuracy: 0.8400
F1 Score: 0.8333
Precision: 0.8696
Recall: 0.8000

Confusion Matrix:
[[88 12]
 [20 80]]
------------------------------------------------------------


Epoch 18/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.06it/s]



Epoch 18/50 - Time: 27.65s
Train Loss: 0.0401
Test Loss: 1.1718

Test Metrics:
Accuracy: 0.8250
F1 Score: 0.8066
Precision: 0.9012
Recall: 0.7300

Confusion Matrix:
[[92  8]
 [27 73]]
------------------------------------------------------------


Epoch 19/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  8.64it/s]



Epoch 19/50 - Time: 25.88s
Train Loss: 0.0206
Test Loss: 1.3500

Test Metrics:
Accuracy: 0.8700
F1 Score: 0.8750
Precision: 0.8426
Recall: 0.9100

Confusion Matrix:
[[83 17]
 [ 9 91]]
------------------------------------------------------------


Epoch 20/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.83it/s]



Epoch 20/50 - Time: 24.21s
Train Loss: 0.0101
Test Loss: 0.9321

Test Metrics:
Accuracy: 0.8700
F1 Score: 0.8687
Precision: 0.8776
Recall: 0.8600

Confusion Matrix:
[[88 12]
 [14 86]]
------------------------------------------------------------


Epoch 21/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.83it/s]



Epoch 21/50 - Time: 26.11s
Train Loss: 0.0514
Test Loss: 0.8758

Test Metrics:
Accuracy: 0.8700
F1 Score: 0.8738
Precision: 0.8491
Recall: 0.9000

Confusion Matrix:
[[84 16]
 [10 90]]
------------------------------------------------------------


Epoch 22/50 [Test]: 100%|██████████| 7/7 [00:00<00:00,  7.19it/s]



Epoch 22/50 - Time: 23.44s
Train Loss: 0.0269
Test Loss: 0.5086

Test Metrics:
Accuracy: 0.8750
F1 Score: 0.8792
Precision: 0.8505
Recall: 0.9100

Confusion Matrix:
[[84 16]
 [ 9 91]]
------------------------------------------------------------


Epoch 23/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  3.78it/s]



Epoch 23/50 - Time: 33.45s
Train Loss: 0.0644
Test Loss: 0.5004

Test Metrics:
Accuracy: 0.9000
F1 Score: 0.9038
Precision: 0.8704
Recall: 0.9400

Confusion Matrix:
[[86 14]
 [ 6 94]]
------------------------------------------------------------


Epoch 24/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  3.96it/s]



Epoch 24/50 - Time: 27.27s
Train Loss: 0.0211
Test Loss: 0.9949

Test Metrics:
Accuracy: 0.8850
F1 Score: 0.8889
Precision: 0.8598
Recall: 0.9200

Confusion Matrix:
[[85 15]
 [ 8 92]]
------------------------------------------------------------


Epoch 25/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.06it/s]



Epoch 25/50 - Time: 25.16s
Train Loss: 0.0205
Test Loss: 0.5693

Test Metrics:
Accuracy: 0.8900
F1 Score: 0.8972
Precision: 0.8421
Recall: 0.9600

Confusion Matrix:
[[82 18]
 [ 4 96]]
------------------------------------------------------------


Epoch 26/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.16it/s]



Epoch 26/50 - Time: 23.36s
Train Loss: 0.0075
Test Loss: 0.7324

Test Metrics:
Accuracy: 0.8550
F1 Score: 0.8557
Precision: 0.8515
Recall: 0.8600

Confusion Matrix:
[[85 15]
 [14 86]]
------------------------------------------------------------


Epoch 27/50 [Test]: 100%|██████████| 7/7 [00:02<00:00,  2.77it/s]



Epoch 27/50 - Time: 33.77s
Train Loss: 0.0118
Test Loss: 1.5524

Test Metrics:
Accuracy: 0.8800
F1 Score: 0.8800
Precision: 0.8800
Recall: 0.8800

Confusion Matrix:
[[88 12]
 [12 88]]
------------------------------------------------------------


Epoch 28/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.30it/s]



Epoch 28/50 - Time: 31.52s
Train Loss: 0.0368
Test Loss: 1.0038

Test Metrics:
Accuracy: 0.8550
F1 Score: 0.8612
Precision: 0.8257
Recall: 0.9000

Confusion Matrix:
[[81 19]
 [10 90]]
------------------------------------------------------------


Epoch 29/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  3.98it/s]



Epoch 29/50 - Time: 40.17s
Train Loss: 0.0118
Test Loss: 1.0404

Test Metrics:
Accuracy: 0.8950
F1 Score: 0.8995
Precision: 0.8624
Recall: 0.9400

Confusion Matrix:
[[85 15]
 [ 6 94]]
------------------------------------------------------------


Epoch 30/50 [Test]: 100%|██████████| 7/7 [00:02<00:00,  3.37it/s]



Epoch 30/50 - Time: 47.18s
Train Loss: 0.0013
Test Loss: 1.6355

Test Metrics:
Accuracy: 0.8850
F1 Score: 0.8930
Precision: 0.8348
Recall: 0.9600

Confusion Matrix:
[[81 19]
 [ 4 96]]
------------------------------------------------------------


Epoch 31/50 [Test]: 100%|██████████| 7/7 [00:02<00:00,  2.97it/s]



Epoch 31/50 - Time: 37.83s
Train Loss: 0.0007
Test Loss: 1.5995

Test Metrics:
Accuracy: 0.8700
F1 Score: 0.8750
Precision: 0.8426
Recall: 0.9100

Confusion Matrix:
[[83 17]
 [ 9 91]]
------------------------------------------------------------


Epoch 32/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.60it/s]



Epoch 32/50 - Time: 29.45s
Train Loss: 0.0006
Test Loss: 1.5833

Test Metrics:
Accuracy: 0.8800
F1 Score: 0.8857
Precision: 0.8455
Recall: 0.9300

Confusion Matrix:
[[83 17]
 [ 7 93]]
------------------------------------------------------------


Epoch 33/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.46it/s]



Epoch 33/50 - Time: 27.25s
Train Loss: 0.0015
Test Loss: 1.1452

Test Metrics:
Accuracy: 0.8750
F1 Score: 0.8780
Precision: 0.8571
Recall: 0.9000

Confusion Matrix:
[[85 15]
 [10 90]]
------------------------------------------------------------


Epoch 34/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  3.55it/s]



Epoch 34/50 - Time: 43.01s
Train Loss: 0.0042
Test Loss: 0.7985

Test Metrics:
Accuracy: 0.8850
F1 Score: 0.8900
Precision: 0.8532
Recall: 0.9300

Confusion Matrix:
[[84 16]
 [ 7 93]]
------------------------------------------------------------


Epoch 35/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.14it/s]



Epoch 35/50 - Time: 39.05s
Train Loss: 0.0512
Test Loss: 2.4173

Test Metrics:
Accuracy: 0.8350
F1 Score: 0.8421
Precision: 0.8073
Recall: 0.8800

Confusion Matrix:
[[79 21]
 [12 88]]
------------------------------------------------------------


Epoch 36/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.88it/s]



Epoch 36/50 - Time: 29.48s
Train Loss: 0.0678
Test Loss: 0.6164

Test Metrics:
Accuracy: 0.8250
F1 Score: 0.8168
Precision: 0.8571
Recall: 0.7800

Confusion Matrix:
[[87 13]
 [22 78]]
------------------------------------------------------------


Epoch 37/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.90it/s]



Epoch 37/50 - Time: 32.57s
Train Loss: 0.0266
Test Loss: 0.7659

Test Metrics:
Accuracy: 0.8550
F1 Score: 0.8599
Precision: 0.8318
Recall: 0.8900

Confusion Matrix:
[[82 18]
 [11 89]]
------------------------------------------------------------


Epoch 38/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.58it/s]



Epoch 38/50 - Time: 30.49s
Train Loss: 0.0154
Test Loss: 1.3861

Test Metrics:
Accuracy: 0.8300
F1 Score: 0.8333
Precision: 0.8173
Recall: 0.8500

Confusion Matrix:
[[81 19]
 [15 85]]
------------------------------------------------------------


Epoch 39/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.21it/s]



Epoch 39/50 - Time: 28.09s
Train Loss: 0.0504
Test Loss: 1.0250

Test Metrics:
Accuracy: 0.8700
F1 Score: 0.8713
Precision: 0.8627
Recall: 0.8800

Confusion Matrix:
[[86 14]
 [12 88]]
------------------------------------------------------------


Epoch 40/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.57it/s]



Epoch 40/50 - Time: 31.44s
Train Loss: 0.0174
Test Loss: 0.7100

Test Metrics:
Accuracy: 0.8650
F1 Score: 0.8571
Precision: 0.9101
Recall: 0.8100

Confusion Matrix:
[[92  8]
 [19 81]]
------------------------------------------------------------


Epoch 41/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.10it/s]



Epoch 41/50 - Time: 29.11s
Train Loss: 0.0260
Test Loss: 1.1929

Test Metrics:
Accuracy: 0.8750
F1 Score: 0.8804
Precision: 0.8440
Recall: 0.9200

Confusion Matrix:
[[83 17]
 [ 8 92]]
------------------------------------------------------------


Epoch 42/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  6.89it/s]



Epoch 42/50 - Time: 27.40s
Train Loss: 0.0215
Test Loss: 1.7649

Test Metrics:
Accuracy: 0.8350
F1 Score: 0.8451
Precision: 0.7965
Recall: 0.9000

Confusion Matrix:
[[77 23]
 [10 90]]
------------------------------------------------------------


Epoch 43/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.39it/s]



Epoch 43/50 - Time: 27.40s
Train Loss: 0.0092
Test Loss: 1.3807

Test Metrics:
Accuracy: 0.8300
F1 Score: 0.8265
Precision: 0.8438
Recall: 0.8100

Confusion Matrix:
[[85 15]
 [19 81]]
------------------------------------------------------------


Epoch 44/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.85it/s]



Epoch 44/50 - Time: 29.32s
Train Loss: 0.0038
Test Loss: 2.5835

Test Metrics:
Accuracy: 0.8400
F1 Score: 0.8447
Precision: 0.8208
Recall: 0.8700

Confusion Matrix:
[[81 19]
 [13 87]]
------------------------------------------------------------


Epoch 45/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.14it/s]



Epoch 45/50 - Time: 29.02s
Train Loss: 0.0011
Test Loss: 1.7973

Test Metrics:
Accuracy: 0.8500
F1 Score: 0.8485
Precision: 0.8571
Recall: 0.8400

Confusion Matrix:
[[86 14]
 [16 84]]
------------------------------------------------------------


Epoch 46/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.89it/s]



Epoch 46/50 - Time: 27.66s
Train Loss: 0.0002
Test Loss: 1.8768

Test Metrics:
Accuracy: 0.8450
F1 Score: 0.8410
Precision: 0.8632
Recall: 0.8200

Confusion Matrix:
[[87 13]
 [18 82]]
------------------------------------------------------------


Epoch 47/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.09it/s]



Epoch 47/50 - Time: 29.70s
Train Loss: 0.0001
Test Loss: 2.1397

Test Metrics:
Accuracy: 0.8500
F1 Score: 0.8500
Precision: 0.8500
Recall: 0.8500

Confusion Matrix:
[[85 15]
 [15 85]]
------------------------------------------------------------


Epoch 48/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.06it/s]



Epoch 48/50 - Time: 30.64s
Train Loss: 0.0003
Test Loss: 2.5125

Test Metrics:
Accuracy: 0.8650
F1 Score: 0.8670
Precision: 0.8544
Recall: 0.8800

Confusion Matrix:
[[85 15]
 [12 88]]
------------------------------------------------------------


Epoch 49/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  4.56it/s]



Epoch 49/50 - Time: 28.27s
Train Loss: 0.0003
Test Loss: 1.8356

Test Metrics:
Accuracy: 0.8600
F1 Score: 0.8586
Precision: 0.8673
Recall: 0.8500

Confusion Matrix:
[[87 13]
 [15 85]]
------------------------------------------------------------


Epoch 50/50 [Test]: 100%|██████████| 7/7 [00:01<00:00,  5.39it/s]


Epoch 50/50 - Time: 28.64s
Train Loss: 0.0002
Test Loss: 2.1025

Test Metrics:
Accuracy: 0.8650
F1 Score: 0.8683
Precision: 0.8476
Recall: 0.8900

Confusion Matrix:
[[84 16]
 [11 89]]
------------------------------------------------------------


In [11]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))
    
# Plot training loss
epochs = range(1, len(train_losses) + 1)
ax1.plot(epochs, train_losses, 'b-', label='Training Loss')
ax1.set_title('Training Loss Over Time')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Loss')
ax1.legend()

# Plot test metrics
for metric in test_metrics:
    ax2.plot(epochs, test_metrics[metric], label=metric.capitalize())
ax2.set_title('Test Metrics Over Time')
ax2.set_xlabel('Epochs')
ax2.set_ylabel('Score')
ax2.legend()

plt.tight_layout()
plt.savefig(f'CNN_model_{model_number}_final_metrics.png')
plt.close()